In [6]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [7]:
file = 'categories_amounts1.csv'

In [8]:
categories_df = pd.read_csv(file, encoding="ISO-8859-1")

In [9]:
categories_df

,Categories,Amount(USD)2008,Amount(USD)2009,Amount(USD)2010,Amount(USD)2011,Amount(USD)2012,Amount(USD)2013,Amount(USD)2014,Amount(USD)2015
0,Biotechnology,"$2,107,706,306","$6,086,891,457","$7,967,040,151","$7,265,458,518","$6,387,455,026","$7,293,211,811","$7,724,704,567","$2,107,706,306"
1,Software,"$2,298,095,000","$2,386,021,661","$3,085,392,930","$3,451,402,996","$3,030,040,605","$3,022,835,162","$4,834,759,542","$2,298,095,000"
2,E-Commerce,"$660,430,304","$549,543,693","$1,941,412,164","$3,424,501,828","$1,986,484,274","$2,976,385,028","$3,894,631,651","$660,430,304"
3,Health Care,"$1,352,517,143","$2,345,619,383","$2,651,334,516","$2,953,479,693","$2,377,364,945","$2,176,283,688","$2,636,599,697","$1,352,517,143"
4,Enterprise Software,"$917,707,308","$1,028,993,578","$1,450,213,882","$1,601,680,966","$1,678,266,418","$2,259,006,351","$2,582,357,623","$917,707,308"
5,Transportation,"$1,352,137,318","$1,042,241,419","$1,353,896,474","$1,661,551,295","$1,741,138,942","$478,553,524","$2,130,257,369","$1,352,137,318"
6,Mobile,"$442,362,477","$379,616,508","$527,293,702","$758,641,110","$947,860,602","$1,623,466,927","$2,130,018,932","$442,362,477"
7,Analytics,"$225,523,777","$493,082,575","$525,131,995","$663,690,896","$262,666,092","$1,023,705,127","$2,026,204,566","$225,523,777"
8,Online Shopping,"$661,593,857","$396,798,027","$592,538,338","$746,603,696","$557,314,478","$609,814,214","$2,009,050,672","$661,593,857"
9,Health and Wellness,"$435,995,243","$433,085,252","$740,212,022","$680,941,936","$764,959,270","$778,390,850","$1,727,893,718","$435,995,243"
10,Curated Web,"$4,550,421,149","$2,063,962,407","$2,877,812,656","$3,233,692,246","$721,997,770","$1,249,176,055","$1,691,192,115","$4,550,421,149"
11,Finance,"$597,812,873","$1,026,118,346","$795,291,039","$400,944,466","$2,389,956,835","$1,171,179,639","$1,538,977,689","$597,812,873"
12,Clean Technology,"$913,105,291","$832,920,066","$1,232,559,034","$1,023,662,441","$663,601,611","$1,421,998,626","$1,365,981,335","$913,105,291"
13,Hospitality,"$257,984,190","$235,212,589","$272,517,602","$2,462,289,565","$1,001,002,404","$386,033,649","$1,256,110,072","$257,984,190"
14,Travel,"$713,011,281","$540,655,994","$1,055,129,323","$506,903,888","$453,977,824","$539,712,551","$1,146,704,999","$713,011,281"
15,Hardware + Software,"$1,283,525,028","$1,063,663,380","$996,114,613","$956,676,586","$681,146,040","$1,143,316,601","$1,030,616,003","$1,283,525,028"
16,Advertising,"$788,406,757","$856,970,561","$1,159,520,917","$968,949,781","$712,497,134","$1,156,011,518","$1,006,944,476","$788,406,757"
17,Education,"$864,539,198","$570,552,414","$775,935,109","$706,496,558","$598,641,630","$602,462,643","$879,375,273","$864,539,198"
18,Social Media,"$244,804,650","$365,689,163","$326,072,461","$1,137,700,669","$621,400,142","$473,242,329","$824,779,590","$244,804,650"
19,Technology,"$379,308,318","$225,443,856","$350,232,163","$395,542,425","$644,069,543","$396,907,202","$804,311,215","$379,308,318"
20,Video,"$273,291,756","$198,356,213","$257,053,167","$348,081,344","$407,155,047","$464,384,328","$776,581,698","$273,291,756"
21,Pharmaceuticals,"$297,611,800","$215,162,000","$391,787,603","$306,680,434","$464,515,255","$828,768,962","$700,748,462","$297,611,800"
22,Semiconductors,"$284,488,595","$305,775,987","$336,710,000","$292,029,782","$317,175,347","$625,394,970","$692,176,184","$284,488,595"
23,Manufacturing,"$228,777,464","$715,119,227","$725,100,896","$364,496,061","$342,026,000","$383,858,864","$687,275,154","$228,777,464"
24,Games,"$669,080,190","$486,801,643","$572,727,441","$429,583,157","$576,118,763","$384,341,513","$656,106,509","$669,080,190"

In [20]:

#connecting to my sql database
rds_connection_string = "root:Lucky0510!@127.0.0.1/InvestmentCategories"
engine = create_engine(f'mysql://{rds_connection_string}')

In [21]:

engine.table_names()

C:\Users\Seanj922\Anaconda4\lib\site-packages\pymysql\cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)

['investmentcategories', 'investmentcategory1']

In [23]:
#Loading data to kickstarter mysql table
categories_df.to_sql(name='investmentcategories', con=engine, if_exists='append', index=False)