In [47]:
import pandas as pd
import matplotlib
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [48]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, func

In [49]:
funding_csv = "funding_08_14.csv"
funding_df = pd.read_csv(funding_csv)
funding_df = funding_df.set_index("Labels")
funding_df

                              2008  2009  2010  2011    2012  2013_2014
Labels
Rounds: angel                  401   290   366   522   573.0       1522
Rounds: seed                   563   715   914  1379  1923.0      10810
Rounds: venture               1704  4230  7014  3079  2971.0      15289
Rounds: convertible_note         1     3     3     4    10.0        605
Rounds: debt_financing          46   170   276   157   177.0       2930
Rounds: grant                    5    69   121   117   114.0        794
Rounds: post_ipo_debt            0     3     2     0     0.0         74
Rounds: post_ipo_equity          4     7     5     1    14.0        314
Rounds: private_equity          17    58    96    83    92.0        630
Rounds: secondary_market         0     1     1     1     NaN         52
Rounds: equity_crowdfunding      0     0     0     0     2.0       2258
Rounds: product_crowdfunding     0     0     0     2     5.0        156
Rounds: undisclosed             52   194   238   344   339.0       2164
Rounds                        2793  5740  9036  5689  6220.0      37598
Acquisitions                  1102  1173  1584  1813  1565.0       2709
IPOs                           110   217   252   222   217.0        386

In [50]:

#connecting to my sql database
rds_connection_string = "root:Lucky0510!@127.0.0.1/funding_types"
engine = create_engine(f'mysql://{rds_connection_string}')

In [51]:
engine.table_names()

C:\Users\Seanj922\Anaconda4\lib\site-packages\pymysql\cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)

['funding_types', 'funding_types1', 'funding_types2']

In [52]:
#Loading data to kickstarter mysql table
funding_df.to_sql(name='funding_types2', con=engine, if_exists='append', index=False)

InternalError: (pymysql.err.InternalError) (1054, "Unknown column '2008' in 'field list'") [SQL: 'INSERT INTO funding_types2 (`2008`, `2009`, `2010`, `2011`, `2012`, `2013_2014`) VALUES (%(2008_m0)s, %(2009_m0)s, %(2010_m0)s, %(2011_m0)s, %(2012_m0)s, %(2013_2014_m0)s), (%(2008_m1)s, %(2009_m1)s, %(2010_m1)s, %(2011_m1)s, %(2012_m1)s, %(2013_2014_m1)s), (%(2008_m2)s, %(2009_m2)s, %(2010_m2)s, %(2011_m2)s, %(2012_m2)s, %(2013_2014_m2)s), (%(2008_m3)s, %(2009_m3)s, %(2010_m3)s, %(2011_m3)s, %(2012_m3)s, %(2013_2014_m3)s), (%(2008_m4)s, %(2009_m4)s, %(2010_m4)s, %(2011_m4)s, %(2012_m4)s, %(2013_2014_m4)s), (%(2008_m5)s, %(2009_m5)s, %(2010_m5)s, %(2011_m5)s, %(2012_m5)s, %(2013_2014_m5)s), (%(2008_m6)s, %(2009_m6)s, %(2010_m6)s, %(2011_m6)s, %(2012_m6)s, %(2013_2014_m6)s), (%(2008_m7)s, %(2009_m7)s, %(2010_m7)s, %(2011_m7)s, %(2012_m7)s, %(2013_2014_m7)s), (%(2008_m8)s, %(2009_m8)s, %(2010_m8)s, %(2011_m8)s, %(2012_m8)s, %(2013_2014_m8)s), (%(2008_m9)s, %(2009_m9)s, %(2010_m9)s, %(2011_m9)s, %(2012_m9)s, %(2013_2014_m9)s), (%(2008_m10)s, %(2009_m10)s, %(2010_m10)s, %(2011_m10)s, %(2012_m10)s, %(2013_2014_m10)s), (%(2008_m11)s, %(2009_m11)s, %(2010_m11)s, %(2011_m11)s, %(2012_m11)s, %(2013_2014_m11)s), (%(2008_m12)s, %(2009_m12)s, %(2010_m12)s, %(2011_m12)s, %(2012_m12)s, %(2013_2014_m12)s), (%(2008_m13)s, %(2009_m13)s, %(2010_m13)s, %(2011_m13)s, %(2012_m13)s, %(2013_2014_m13)s), (%(2008_m14)s, %(2009_m14)s, %(2010_m14)s, %(2011_m14)s, %(2012_m14)s, %(2013_2014_m14)s), (%(2008_m15)s, %(2009_m15)s, %(2010_m15)s, %(2011_m15)s, %(2012_m15)s, %(2013_2014_m15)s)'] [parameters: {'2008_m0': 401, '2009_m0': 290, '2010_m0': 366, '2011_m0': 522, '2012_m0': 573.0, '2013_2014_m0': 1522, '2008_m1': 563, '2009_m1': 715, '2010_m1': 914, '2011_m1': 1379, '2012_m1': 1923.0, '2013_2014_m1': 10810, '2008_m2': 1704, '2009_m2': 4230, '2010_m2': 7014, '2011_m2': 3079, '2012_m2': 2971.0, '2013_2014_m2': 15289, '2008_m3': 1, '2009_m3': 3, '2010_m3': 3, '2011_m3': 4, '2012_m3': 10.0, '2013_2014_m3': 605, '2008_m4': 46, '2009_m4': 170, '2010_m4': 276, '2011_m4': 157, '2012_m4': 177.0, '2013_2014_m4': 2930, '2008_m5': 5, '2009_m5': 69, '2010_m5': 121, '2011_m5': 117, '2012_m5': 114.0, '2013_2014_m5': 794, '2008_m6': 0, '2009_m6': 3, '2010_m6': 2, '2011_m6': 0, '2012_m6': 0.0, '2013_2014_m6': 74, '2008_m7': 4, '2009_m7': 7, '2010_m7': 5, '2011_m7': 1, '2012_m7': 14.0, '2013_2014_m7': 314, '2008_m8': 17, '2009_m8': 58, '2010_m8': 96, '2011_m8': 83, '2012_m8': 92.0, '2013_2014_m8': 630, '2008_m9': 0, '2009_m9': 1, '2010_m9': 1, '2011_m9': 1, '2012_m9': None, '2013_2014_m9': 52, '2008_m10': 0, '2009_m10': 0, '2010_m10': 0, '2011_m10': 0, '2012_m10': 2.0, '2013_2014_m10': 2258, '2008_m11': 0, '2009_m11': 0, '2010_m11': 0, '2011_m11': 2, '2012_m11': 5.0, '2013_2014_m11': 156, '2008_m12': 52, '2009_m12': 194, '2010_m12': 238, '2011_m12': 344, '2012_m12': 339.0, '2013_2014_m12': 2164, '2008_m13': 2793, '2009_m13': 5740, '2010_m13': 9036, '2011_m13': 5689, '2012_m13': 6220.0, '2013_2014_m13': 37598, '2008_m14': 1102, '2009_m14': 1173, '2010_m14': 1584, '2011_m14': 1813, '2012_m14': 1565.0, '2013_2014_m14': 2709, '2008_m15': 110, '2009_m15': 217, '2010_m15': 252, '2011_m15': 222, '2012_m15': 217.0, '2013_2014_m15': 386}] (Background on this error at: http://sqlalche.me/e/2j85)